name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build ./backend --file backend/Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}"/java-academy-2021-backend:latest;
           docker build ./frontend --file frontend/Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}"/java-academy-2021-frontend:latest
    - name: Push image to Docker Registry
      run: docker push "${{ secrets.DOCKER_USERNAME }}"/java-academy-2021-backend:latest;
           docker push "${{ secrets.DOCKER_USERNAME }}"/java-academy-2021-frontend:latest
